#!/bin/sh

# Start daemon if it is not running already
if ! pgrep -f 'python ./mytunes' > /dev/null
then
    test $1 = 'status' && exit 1
    cd `dirname $0`
    python ./mytunes
fi

# Send command to mytunes daemon
{
    echo "$@"
    echo quit
} | nc localhost 12345
